# Generated by Django 5.2.3 on 2025-09-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0022_alter_classroom_options_alter_mealrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(help_text='Tên lớp học', max_length=50),
        ),
    ]
