# Generated by Django 5.2.3 on 2025-09-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0023_alter_classroom_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('name', 'term'), name='unique_classroom_name_term', violation_error_message='Lớp học với tên này đã tồn tại trong niên khóa này.'),
        ),
    ]
